# Generated by Django 2.0.7 on 2018-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
