# Generated by Django 2.0.7 on 2018-10-01 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('choice', models.CharField(choices=[('~30일 50000원', '~30일 50000원'), ('31일~45일 72000원', '31일~45일 72000원'), ('46일~60일 90000원', '46일~60일 90000원'), ('~30일 무료 10개의 포스팅', '~30일 무료 10개의 포스팅')], max_length=30)),
                ('email', models.CharField(max_length=70)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='ad/%Y/%m/%d/')),
                ('title', models.CharField(max_length=40)),
                ('web', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('exposure', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
